// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>VoidSounds</title><script src=\"https://unpkg.com/htmx.org@2/dist/htmx.min.js\"></script><!-- Пока используем Tailwind через CDN для простоты --><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-zinc-950 text-white min-h-screen\"><div class=\"flex items-center justify-center min-h-screen\"><div class=\"text-center\"><h1 class=\"text-7xl font-bold tracking-tighter mb-4 bg-gradient-to-r from-violet-400 to-fuchsia-500 bg-clip-text text-transparent\">VoidSounds</h1><p class=\"text-xl text-zinc-400 mb-10\">Платформа для организации музыкальных мероприятий</p><button class=\"bg-violet-600 hover:bg-violet-700 transition px-10 py-4 rounded-2xl text-lg font-medium\" hx-get=\"/ping\" hx-swap=\"afterend\">Проверить HTMX</button></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
